git submodule add -b master https://github.com/c0001/entropy-windresize.git elements/submodules/entropy-windresize
git submodule add -b master https://github.com/c0001/entropy-undo-tree.git elements/submodules/entropy-undo-tree
git submodule add -b master https://github.com/yjwen/org-reveal.git elements/submodules/org-reveal
git submodule add -b master https://github.com/tomoya/search-web.el.git elements/submodules/search-web.el
git submodule add -b master https://github.com/jinzhu/zeal-at-point.git elements/submodules/zeal-at-point
git submodule add -b master https://github.com/seagle0128/doom-modeline.git elements/submodules/doom-modeline
git submodule add -b master https://github.com/honmaple/emacs-maple-preview.git elements/submodules/emacs-maple-preview
git submodule add -b master https://github.com/mickeynp/makey.git elements/submodules/makey
git submodule add -b master https://github.com/mattfidler/nsis-mode.git elements/submodules/nsis-mode
git submodule add -b master https://github.com/owainlewis/emacs-color-themes.git elements/submodules/emacs-color-themes
git submodule add -b master https://github.com/jwiegley/emacs-async.git elements/submodules/emacs-async
git submodule add -b master https://github.com/Wilfred/elisp-refs.git elements/submodules/elisp-refs
git submodule add -b master https://github.com/skeeto/elfeed.git elements/submodules/elfeed
git submodule add -b master https://github.com/thierryvolpiatto/eldoc-eval.git elements/submodules/eldoc-eval
git submodule add -b master https://github.com/tumashu/el2org.git elements/submodules/el2org
git submodule add -b master https://github.com/manuel-uberti/doneburn-theme.git elements/submodules/doneburn-theme
git submodule add -b master https://github.com/philiparvidsson/GitHub-Theme-for-Emacs.git elements/submodules/GitHub-Theme-for-Emacs
git submodule add -b master https://github.com/xcwen/ac-php.git elements/submodules/ac-php
git submodule add -b master https://github.com/jwiegley/alert.git elements/submodules/alert
git submodule add -b master https://github.com/jtbm37/all-the-icons-dired.git elements/submodules/all-the-icons-dired
git submodule add -b master https://github.com/domtronn/all-the-icons.el.git elements/submodules/all-the-icons.el
git submodule add -b master https://github.com/proofit404/anaconda-mode.git elements/submodules/anaconda-mode
git submodule add -b master https://github.com/whitlockjc/atom-dark-theme-emacs.git elements/submodules/atom-dark-theme-emacs
git submodule add -b master https://github.com/jonathanchu/atom-one-dark-theme.git elements/submodules/atom-one-dark-theme
git submodule add -b master https://github.com/alpha22jp/atomic-chrome.git elements/submodules/atomic-chrome
git submodule add -b master https://github.com/auto-complete/auto-complete.git elements/submodules/auto-complete
git submodule add -b master https://github.com/ncaq/auto-sudoedit.git elements/submodules/auto-sudoedit
git submodule add -b master https://github.com/abo-abo/auto-yasnippet.git elements/submodules/auto-yasnippet
git submodule add -b master https://github.com/abo-abo/avy.git elements/submodules/avy
git submodule add -b master https://github.com/dholm/benchmark-init-el.git elements/submodules/benchmark-init-el
git submodule add -b master https://github.com/cute-jumper/bing-dict.el.git elements/submodules/bing-dict.el
git submodule add -b master https://github.com/jimeh/birds-of-paradise-plus-theme.el.git elements/submodules/birds-of-paradise-plus-theme.el
git submodule add -b master https://github.com/rmuslimov/browse-at-remote.git elements/submodules/browse-at-remote
git submodule add -b master https://github.com/T-J-Teru/browse-kill-ring.git elements/submodules/browse-kill-ring
git submodule add -b master https://github.com/lukhas/buffer-move.git elements/submodules/buffer-move
git submodule add -b master https://github.com/xwl/cal-china-x.git elements/submodules/cal-china-x
git submodule add -b master https://github.com/xuchunyang/chinese-word-at-point.el.git elements/submodules/chinese-word-at-point.el
git submodule add -b master https://github.com/purcell/color-theme-sanityinc-tomorrow.git elements/submodules/color-theme-sanityinc-tomorrow
git submodule add -b master https://github.com/marktran/color-theme-ujelly.git elements/submodules/color-theme-ujelly
git submodule add -b master https://github.com/lewang/command-log-mode.git elements/submodules/command-log-mode
git submodule add -b master https://github.com/proofit404/company-anaconda.git elements/submodules/company-anaconda
git submodule add -b master https://github.com/randomphrase/company-c-headers.git elements/submodules/company-c-headers
git submodule add -b master https://github.com/Sarcasm/company-irony.git elements/submodules/company-irony
git submodule add -b master https://github.com/company-mode/company-mode.git elements/submodules/company-mode
git submodule add -b master https://github.com/tumashu/company-posframe.git elements/submodules/company-posframe
git submodule add -b master https://github.com/expez/company-quickhelp.git elements/submodules/company-quickhelp
git submodule add -b master https://github.com/Alexander-Miller/company-shell.git elements/submodules/company-shell
git submodule add -b master https://github.com/proofit404/company-tern.git elements/submodules/company-tern
git submodule add -b master https://github.com/osv/company-web.git elements/submodules/company-web
git submodule add -b master https://github.com/sjrmanning/darkokai.git elements/submodules/darkokai
git submodule add -b master https://github.com/magnars/dash.el.git elements/submodules/dash.el
git submodule add -b master https://github.com/dgutov/diff-hl.git elements/submodules/diff-hl
git submodule add -b master https://github.com/myrjola/diminish.el.git elements/submodules/diminish.el
git submodule add -b master https://github.com/Fuco1/dired-hacks.git elements/submodules/dired-hacks
git submodule add -b master https://github.com/emacsmirror/dired-quick-sort.git elements/submodules/dired-quick-sort
git submodule add -b master https://github.com/purcell/disable-mouse.git elements/submodules/disable-mouse
git submodule add -b master https://github.com/emacsmirror/discover-my-major.git elements/submodules/discover-my-major
git submodule add -b master https://github.com/zonuexe/emacs-copyit.git elements/submodules/emacs-copyit
git submodule add -b master https://github.com/hlissner/emacs-counsel-css.git elements/submodules/emacs-counsel-css
git submodule add -b master https://github.com/hlissner/emacs-doom-themes.git elements/submodules/emacs-doom-themes
git submodule add -b master https://github.com/syohex/emacs-git-messenger.git elements/submodules/emacs-git-messenger
git submodule add -b master https://github.com/syohex/emacs-helm-ag.git elements/submodules/emacs-helm-ag
git submodule add -b master https://github.com/hniksic/emacs-htmlize.git elements/submodules/emacs-htmlize
git submodule add -b master https://github.com/WammKD/emacs-klere-theme.git elements/submodules/emacs-klere-theme
git submodule add -b master https://github.com/cpaulik/emacs-material-theme.git elements/submodules/emacs-material-theme
git submodule add -b master https://github.com/skeeto/emacs-memoize.git elements/submodules/emacs-memoize
git submodule add -b master https://github.com/skeeto/emacs-web-server.git elements/submodules/emacs-simple-httpd
git submodule add -b master https://github.com/syohex/emacs-smeargle.git elements/submodules/emacs-smeargle
git submodule add -b master https://github.com/eschulte/emacs-web-server.git elements/submodules/emacs-web-server
git submodule add -b master https://github.com/ahyatt/emacs-websocket.git elements/submodules/emacs-websocket
git submodule add -b master https://github.com/justbur/emacs-which-key.git elements/submodules/emacs-which-key
git submodule add -b master https://github.com/smihica/emmet-mode.git elements/submodules/emmet-mode
git submodule add -b master https://github.com/jschaf/esup.git elements/submodules/esup
git submodule add -b master https://github.com/wasamasa/eyebrowse.git elements/submodules/eyebrowse
git submodule add -b master https://github.com/rejeep/f.el.git elements/submodules/f.el
git submodule add -b master https://github.com/magit/ghub.git elements/submodules/ghub
git submodule add -b master https://github.com/magit/git-modes.git elements/submodules/git-modes
git submodule add -b master https://github.com/emacsmirror/git-timemachine.git elements/submodules/git-timemachine
git submodule add -b master https://github.com/tekai/gntp.el.git elements/submodules/gntp.el
git submodule add -b master https://github.com/dominikh/go-mode.el.git elements/submodules/go-mode.el
git submodule add -b master https://github.com/atykhonov/google-translate.git elements/submodules/google-translate
git submodule add -b master https://github.com/wasamasa/gotham-theme.git elements/submodules/gotham-theme
git submodule add -b master https://github.com/vermiculus/graphql.el.git elements/submodules/graphql.el
git submodule add -b master https://github.com/emacs-helm/helm.git elements/submodules/helm
git submodule add -b master https://github.com/DarthFennec/highlight-indent-guides.git elements/submodules/highlight-indent-guides
git submodule add -b master https://github.com/tsdh/highlight-parentheses.el.git elements/submodules/highlight-parentheses.el
git submodule add -b master https://github.com/tarsius/hl-todo.git elements/submodules/hl-todo
git submodule add -b master https://github.com/abo-abo/hydra.git elements/submodules/hydra
git submodule add -b master https://github.com/netguy204/imp.el.git elements/submodules/imp.el
git submodule add -b master https://github.com/mkcms/interactive-align.git elements/submodules/interactive-align
git submodule add -b master https://github.com/ikirill/irony-eldoc.git elements/submodules/irony-eldoc
git submodule add -b master https://github.com/Sarcasm/irony-mode.git elements/submodules/irony-mode
git submodule add -b master https://github.com/alexmurray/ivy-xref.git elements/submodules/ivy-xref
git submodule add -b master https://github.com/mooz/js2-mode.git elements/submodules/js2-mode
git submodule add -b master https://github.com/magnars/js2-refactor.el.git elements/submodules/js2-refactor.el
git submodule add -b master https://github.com/joshwnj/json-mode.git elements/submodules/json-mode
git submodule add -b master https://github.com/gongo/json-reformat.git elements/submodules/json-reformat
git submodule add -b master https://github.com/Sterlingg/json-snatcher.git elements/submodules/json-snatcher
git submodule add -b master https://github.com/aki2o/log4e.git elements/submodules/log4e
git submodule add -b master https://github.com/Wilfred/loop.el.git elements/submodules/loop.el
git submodule add -b master https://github.com/immerrr/lua-mode.git elements/submodules/lua-mode
git submodule add -b master https://github.com/joddie/macrostep.git elements/submodules/macrostep
git submodule add -b master https://github.com/magit/magit.git elements/submodules/magit
git submodule add -b master https://github.com/jtatarik/magit-gitflow.git elements/submodules/magit-gitflow
git submodule add -b master https://github.com/magit/magit-popup.git elements/submodules/magit-popup
git submodule add -b master https://github.com/emacsorphanage/magit-svn.git elements/submodules/magit-svn
git submodule add -b master https://github.com/jrblevin/markdown-mode.git elements/submodules/markdown-mode
git submodule add -b master https://github.com/ancane/markdown-preview-mode.git elements/submodules/markdown-preview-mode
git submodule add -b master https://github.com/purcell/mode-line-bell.git elements/submodules/mode-line-bell
git submodule add -b master https://github.com/magnars/multiple-cursors.el.git elements/submodules/multiple-cursors.el
git submodule add -b master https://github.com/Malabarba/names.git elements/submodules/names
git submodule add -b master https://github.com/emacsmirror/openwith.git elements/submodules/openwith
git submodule add -b master https://github.com/emacsorphanage/org-bullets.git elements/submodules/org-bullets
git submodule add -b master https://github.com/abo-abo/org-download.git elements/submodules/org-download
git submodule add -b master https://github.com/lolownia/org-pomodoro.git elements/submodules/org-pomodoro
git submodule add -b master https://github.com/larstvei/ox-gfm.git elements/submodules/ox-gfm
git submodule add -b master https://github.com/purcell/page-break-lines.git elements/submodules/page-break-lines
git submodule add -b master https://github.com/emacs-php/php-mode.git elements/submodules/php-mode
git submodule add -b master https://github.com/TatriX/pomidor.git elements/submodules/pomidor
git submodule add -b master https://github.com/QBobWatson/poporg.git elements/submodules/poporg
git submodule add -b master https://github.com/auto-complete/popup-el.git elements/submodules/popup-el
git submodule add -b master https://github.com/m2ym/popwin-el.git elements/submodules/popwin-el
git submodule add -b master https://github.com/emacsmirror/pos-tip.git elements/submodules/pos-tip
git submodule add -b master https://github.com/tumashu/posframe.git elements/submodules/posframe
git submodule add -b master https://github.com/milkypostman/powerline.git elements/submodules/powerline
git submodule add -b master https://github.com/paetzke/py-autopep8.el.git elements/submodules/py-autopep8.el
git submodule add -b master https://github.com/tumashu/pyim.git elements/submodules/pyim
git submodule add -b master https://github.com/tumashu/pyim-basedict.git elements/submodules/pyim-basedict
git submodule add -b master https://github.com/proofit404/pythonic.git elements/submodules/pythonic
git submodule add -b master https://github.com/Fanael/rainbow-delimiters.git elements/submodules/rainbow-delimiters
git submodule add -b master https://github.com/emacsmirror/rainbow-mode.git elements/submodules/rainbow-mode
git submodule add -b master https://github.com/magnars/s.el.git elements/submodules/s.el
git submodule add -b master https://github.com/kyagi/shell-pop-el.git elements/submodules/shell-pop-el
git submodule add -b master https://gitlab.com/bennya/shrink-path.el.git elements/submodules/shrink-path.el
git submodule add -b master https://github.com/skeeto/skewer-mode.git elements/submodules/skewer-mode
git submodule add -b master https://github.com/TheBB/spaceline.git elements/submodules/spaceline
git submodule add -b master https://github.com/domtronn/spaceline-all-the-icons.el.git elements/submodules/spaceline-all-the-icons.el
git submodule add -b master https://github.com/nashamri/spacemacs-theme.git elements/submodules/spacemacs-theme
git submodule add -b master https://github.com/srcery-colors/srcery-emacs.git elements/submodules/srcery-emacs
git submodule add -b master https://github.com/magit/ssh-agency.git elements/submodules/ssh-agency
git submodule add -b master https://github.com/abo-abo/swiper.git elements/submodules/swiper
git submodule add -b master https://github.com/wolray/symbol-overlay.git elements/submodules/symbol-overlay
git submodule add -b master https://github.com/ternjs/tern.git elements/submodules/tern
git submodule add -b master https://github.com/snosov1/toc-org.git elements/submodules/toc-org
git submodule add -b master https://github.com/volrath/treepy.el.git elements/submodules/treepy.el
git submodule add -b master https://github.com/jwiegley/use-package.git elements/submodules/use-package
git submodule add -b master https://github.com/kanru/uuidgen-el.git elements/submodules/uuidgen-el
git submodule add -b master https://github.com/benma/visual-regexp.el.git elements/submodules/visual-regexp.el
git submodule add -b master https://github.com/k-talo/volatile-highlights.el.git elements/submodules/volatile-highlights.el
git submodule add -b master https://github.com/yasuyk/web-beautify.git elements/submodules/web-beautify
git submodule add -b master https://github.com/osv/web-completion-data.git elements/submodules/web-completion-data
git submodule add -b master https://github.com/fxbois/web-mode.git elements/submodules/web-mode
git submodule add -b master https://github.com/nikolas/window-number.git elements/submodules/window-number
git submodule add -b master https://github.com/magit/with-editor.git elements/submodules/with-editor
git submodule add -b master https://github.com/dkogan/xcscope.el.git elements/submodules/xcscope.el
git submodule add -b master https://github.com/joaotavora/yasnippet.git elements/submodules/yasnippet
git submodule add -b master https://github.com/AndreaCrotti/yasnippet-snippets.git elements/submodules/yasnippet-snippets
git submodule add -b master https://github.com/xuchunyang/youdao-dictionary.el.git elements/submodules/youdao-dictionary.el
git submodule add -b master https://github.com/magit/transient.git elements/submodules/transient
git submodule add -b master https://github.com/emacs-w3m/emacs-w3m.git elements/submodules/emacs-w3m
git submodule add -b master https://github.com/Malabarba/beacon.git elements/submodules/beacon
git submodule add -b master https://github.com/asok/all-the-icons-ivy.git elements/submodules/all-the-icons-ivy
git submodule add -b master https://github.com/dieggsy/eterm-256color.git elements/submodules/eterm-256color
git submodule add -b master https://github.com/atomontage/xterm-color.git elements/submodules/xterm-color
git submodule add -b master https://github.com/wasamasa/shackle.git elements/submodules/shackle
git submodule add -b master https://github.com/Yevgnen/ivy-rich.git elements/submodules/ivy-rich
