(defvar owner
  '((:repo
     "youdao-dictionary.el"
     :uri
     "https://github.com/xuchunyang/youdao-dictionary.el.git")
    (:repo
     "yasnippet-snippets"
     :uri
     "https://github.com/AndreaCrotti/yasnippet-snippets.git")
    (:repo
     "yasnippet"
     :uri
     "https://github.com/joaotavora/yasnippet.git")
    (:repo
     "xcscope.el"
     :uri
     "https://github.com/dkogan/xcscope.el.git")
    (:repo
     "with-editor"
     :uri
     "https://github.com/magit/with-editor.git")
    (:repo
     "window-number"
     :uri
     "https://github.com/nikolas/window-number.git")
    (:repo
     "web-mode"
     :uri
     "https://github.com/fxbois/web-mode.git")
    (:repo
     "web-completion-data"
     :uri
     "https://github.com/osv/web-completion-data.git")
    (:repo
     "web-beautify"
     :uri
     "https://github.com/yasuyk/web-beautify.git")
    (:repo
     "w3m"
     :uri
     "https://github.com/thomasf/w3m.git")
    (:repo
     "volatile-highlights.el"
     :uri
     "https://github.com/k-talo/volatile-highlights.el.git")
    (:repo
     "visual-regexp.el"
     :uri
     "https://github.com/benma/visual-regexp.el.git")
    (:repo
     "uuidgen-el"
     :uri
     "https://github.com/kanru/uuidgen-el.git")
    (:repo
     "use-package"
     :uri
     "https://github.com/jwiegley/use-package.git")
    (:repo
     "treepy.el"
     :uri
     "https://github.com/volrath/treepy.el.git")
    (:repo
     "toc-org"
     :uri
     "https://github.com/snosov1/toc-org.git")
    (:repo
     "tern"
     :uri
     "https://github.com/ternjs/tern.git")
    (:repo
     "symbol-overlay"
     :uri
     "https://github.com/wolray/symbol-overlay.git")
    (:repo
     "swiper"
     :uri
     "https://github.com/abo-abo/swiper.git")
    (:repo
     "ssh-agency"
     :uri
     "https://github.com/magit/ssh-agency.git")
    (:repo
     "srcery-emacs"
     :uri
     "https://github.com/srcery-colors/srcery-emacs.git")
    (:repo
     "spacemacs-theme"
     :uri
     "https://github.com/nashamri/spacemacs-theme.git")
    (:repo
     "spaceline-all-the-icons.el"
     :uri
     "https://github.com/domtronn/spaceline-all-the-icons.el.git")
    (:repo
     "spaceline"
     :uri
     "https://github.com/TheBB/spaceline.git")
    (:repo
     "skewer-mode"
     :uri
     "https://github.com/skeeto/skewer-mode.git")
    (:repo
     "shrink-path.el"
     :uri
     "https://gitlab.com/bennya/shrink-path.el.git")
    (:repo
     "shell-pop-el"
     :uri
     "https://github.com/kyagi/shell-pop-el.git")
    (:repo
     "s.el"
     :uri
     "https://github.com/magnars/s.el.git")
    (:repo
     "rainbow-mode"
     :uri
     "https://github.com/emacsmirror/rainbow-mode.git")
    (:repo
     "rainbow-delimiters"
     :uri
     "https://github.com/Fanael/rainbow-delimiters.git")
    (:repo
     "pythonic"
     :uri
     "https://github.com/proofit404/pythonic.git")
    (:repo
     "pyim-basedict"
     :uri
     "https://github.com/tumashu/pyim-basedict.git")
    (:repo
     "pyim"
     :uri
     "https://github.com/tumashu/pyim.git")
    (:repo
     "py-autopep8.el"
     :uri
     "https://github.com/paetzke/py-autopep8.el.git")
    (:repo
     "powerline"
     :uri
     "https://github.com/milkypostman/powerline.git")
    (:repo
     "posframe"
     :uri
     "https://github.com/tumashu/posframe.git")
    (:repo
     "pos-tip"
     :uri
     "https://github.com/emacsmirror/pos-tip.git")
    (:repo
     "popwin-el"
     :uri
     "https://github.com/m2ym/popwin-el.git")
    (:repo
     "popup-el"
     :uri
     "https://github.com/auto-complete/popup-el.git")
    (:repo
     "poporg"
     :uri
     "https://github.com/QBobWatson/poporg.git")
    (:repo
     "pomidor"
     :uri
     "https://github.com/TatriX/pomidor.git")
    (:repo
     "php-mode"
     :uri
     "https://github.com/emacs-php/php-mode.git")
    (:repo
     "page-break-lines"
     :uri
     "https://github.com/purcell/page-break-lines.git")
    (:repo
     "ox-gfm"
     :uri
     "https://github.com/larstvei/ox-gfm.git")
    (:repo
     "org-pomodoro"
     :uri
     "https://github.com/lolownia/org-pomodoro.git")
    (:repo
     "org-download"
     :uri
     "https://github.com/abo-abo/org-download.git")
    (:repo
     "org-bullets"
     :uri
     "https://github.com/emacsorphanage/org-bullets.git")
    (:repo
     "openwith"
     :uri
     "https://github.com/emacsmirror/openwith.git")
    (:repo
     "names"
     :uri
     "https://github.com/Malabarba/names.git")
    (:repo
     "multiple-cursors.el"
     :uri
     "https://github.com/magnars/multiple-cursors.el.git")
    (:repo
     "mode-line-bell"
     :uri
     "https://github.com/purcell/mode-line-bell.git")
    (:repo
     "markdown-preview-mode"
     :uri
     "https://github.com/ancane/markdown-preview-mode.git")
    (:repo
     "markdown-mode"
     :uri
     "https://github.com/jrblevin/markdown-mode.git")
    (:repo
     "magit-svn"
     :uri
     "https://github.com/emacsorphanage/magit-svn.git")
    (:repo
     "magit-popup"
     :uri
     "https://github.com/magit/magit-popup.git")
    (:repo
     "magit-gitflow"
     :uri
     "https://github.com/jtatarik/magit-gitflow.git")
    (:repo
     "magit"
     :uri
     "https://github.com/magit/magit.git")
    (:repo
     "macrostep"
     :uri
     "https://github.com/joddie/macrostep.git")
    (:repo
     "lua-mode"
     :uri
     "https://github.com/immerrr/lua-mode.git")
    (:repo
     "loop.el"
     :uri
     "https://github.com/Wilfred/loop.el.git")
    (:repo
     "log4e"
     :uri
     "https://github.com/aki2o/log4e.git")
    (:repo
     "json-snatcher"
     :uri
     "https://github.com/Sterlingg/json-snatcher.git")
    (:repo
     "json-reformat"
     :uri
     "https://github.com/gongo/json-reformat.git")
    (:repo
     "json-mode"
     :uri
     "https://github.com/joshwnj/json-mode.git")
    (:repo
     "js2-refactor.el"
     :uri
     "https://github.com/magnars/js2-refactor.el.git")
    (:repo
     "js2-mode"
     :uri
     "https://github.com/mooz/js2-mode.git")
    (:repo
     "ivy-xref"
     :uri
     "https://github.com/alexmurray/ivy-xref.git")
    (:repo
     "irony-mode"
     :uri
     "https://github.com/Sarcasm/irony-mode.git")
    (:repo
     "irony-eldoc"
     :uri
     "https://github.com/ikirill/irony-eldoc.git")
    (:repo
     "interactive-align"
     :uri
     "https://github.com/mkcms/interactive-align.git")
    (:repo
     "imp.el"
     :uri
     "https://github.com/netguy204/imp.el.git")
    (:repo
     "hydra"
     :uri
     "https://github.com/abo-abo/hydra.git")
    (:repo
     "hl-todo"
     :uri
     "https://github.com/tarsius/hl-todo.git")
    (:repo
     "highlight-parentheses.el"
     :uri
     "https://github.com/tsdh/highlight-parentheses.el.git")
    (:repo
     "highlight-indent-guides"
     :uri
     "https://github.com/DarthFennec/highlight-indent-guides.git")
    (:repo
     "helm"
     :uri
     "https://github.com/emacs-helm/helm.git")
    (:repo
     "graphql.el"
     :uri
     "https://github.com/vermiculus/graphql.el.git")
    (:repo
     "gotham-theme"
     :uri
     "https://github.com/wasamasa/gotham-theme.git")
    (:repo
     "google-translate"
     :uri
     "https://github.com/atykhonov/google-translate.git")
    (:repo
     "go-mode.el"
     :uri
     "https://github.com/dominikh/go-mode.el.git")
    (:repo
     "gntp.el"
     :uri
     "https://github.com/tekai/gntp.el.git")
    (:repo
     "git-timemachine"
     :uri
     "https://github.com/emacsmirror/git-timemachine.git")
    (:repo
     "git-modes"
     :uri
     "https://github.com/magit/git-modes.git")
    (:repo
     "ghub"
     :uri
     "https://github.com/magit/ghub.git")
    (:repo
     "f.el"
     :uri
     "https://github.com/rejeep/f.el.git")
    (:repo
     "eyebrowse"
     :uri
     "https://github.com/wasamasa/eyebrowse.git")
    (:repo
     "esup"
     :uri
     "https://github.com/jschaf/esup.git")
    (:repo
     "emmet-mode"
     :uri
     "https://github.com/smihica/emmet-mode.git")
    (:repo
     "emacs-which-key"
     :uri
     "https://github.com/justbur/emacs-which-key.git")
    (:repo
     "emacs-websocket"
     :uri
     "https://github.com/ahyatt/emacs-websocket.git")
    (:repo
     "emacs-web-server"
     :uri
     "https://github.com/eschulte/emacs-web-server.git")
    (:repo
     "emacs-smeargle"
     :uri
     "https://github.com/syohex/emacs-smeargle.git")
    (:repo
     "emacs-simple-httpd"
     :uri
     "https://github.com/skeeto/emacs-web-server.git")
    (:repo
     "emacs-memoize"
     :uri
     "https://github.com/skeeto/emacs-memoize.git")
    (:repo
     "emacs-material-theme"
     :uri
     "https://github.com/cpaulik/emacs-material-theme.git")
    (:repo
     "emacs-klere-theme"
     :uri
     "https://github.com/WammKD/emacs-klere-theme.git")
    (:repo
     "emacs-htmlize"
     :uri
     "https://github.com/hniksic/emacs-htmlize.git")
    (:repo
     "emacs-helm-ag"
     :uri
     "https://github.com/syohex/emacs-helm-ag.git")
    (:repo
     "emacs-git-messenger"
     :uri
     "https://github.com/syohex/emacs-git-messenger.git")
    (:repo
     "emacs-doom-themes"
     :uri
     "https://github.com/hlissner/emacs-doom-themes.git")
    (:repo
     "emacs-counsel-css"
     :uri
     "https://github.com/hlissner/emacs-counsel-css.git")
    (:repo
     "emacs-copyit"
     :uri
     "https://github.com/zonuexe/emacs-copyit.git")
    (:repo
     "discover-my-major"
     :uri
     "https://github.com/emacsmirror/discover-my-major.git")
    (:repo
     "disable-mouse"
     :uri
     "https://github.com/purcell/disable-mouse.git")
    (:repo
     "dired-quick-sort"
     :uri
     "https://github.com/emacsmirror/dired-quick-sort.git")
    (:repo
     "dired-hacks"
     :uri
     "https://github.com/Fuco1/dired-hacks.git")
    (:repo
     "diminish.el"
     :uri
     "https://github.com/myrjola/diminish.el.git")
    (:repo
     "diff-hl"
     :uri
     "https://github.com/dgutov/diff-hl.git")
    (:repo
     "dash.el"
     :uri
     "https://github.com/magnars/dash.el.git")
    (:repo
     "darkokai"
     :uri
     "https://github.com/sjrmanning/darkokai.git")
    (:repo
     "company-web"
     :uri
     "https://github.com/osv/company-web.git")
    (:repo
     "company-tern"
     :uri
     "https://github.com/proofit404/company-tern.git")
    (:repo
     "company-shell"
     :uri
     "https://github.com/Alexander-Miller/company-shell.git")
    (:repo
     "company-quickhelp"
     :uri
     "https://github.com/expez/company-quickhelp.git")
    (:repo
     "company-posframe"
     :uri
     "https://github.com/tumashu/company-posframe.git")
    (:repo
     "company-mode"
     :uri
     "https://github.com/company-mode/company-mode.git")
    (:repo
     "company-irony"
     :uri
     "https://github.com/Sarcasm/company-irony.git")
    (:repo
     "company-c-headers"
     :uri
     "https://github.com/randomphrase/company-c-headers.git")
    (:repo
     "company-anaconda"
     :uri
     "https://github.com/proofit404/company-anaconda.git")
    (:repo
     "command-log-mode"
     :uri
     "https://github.com/lewang/command-log-mode.git")
    (:repo
     "color-theme-ujelly"
     :uri
     "https://github.com/marktran/color-theme-ujelly.git")
    (:repo
     "color-theme-sanityinc-tomorrow"
     :uri
     "https://github.com/purcell/color-theme-sanityinc-tomorrow.git")
    (:repo
     "chinese-word-at-point.el"
     :uri
     "https://github.com/xuchunyang/chinese-word-at-point.el.git")
    (:repo
     "cal-china-x"
     :uri
     "https://github.com/xwl/cal-china-x.git")
    (:repo
     "buffer-move"
     :uri
     "https://github.com/lukhas/buffer-move.git")
    (:repo
     "browse-kill-ring"
     :uri
     "https://github.com/T-J-Teru/browse-kill-ring.git")
    (:repo
     "browse-at-remote"
     :uri
     "https://github.com/rmuslimov/browse-at-remote.git")
    (:repo
     "birds-of-paradise-plus-theme.el"
     :uri
     "https://github.com/jimeh/birds-of-paradise-plus-theme.el.git")
    (:repo
     "bing-dict.el"
     :uri
     "https://github.com/cute-jumper/bing-dict.el.git")
    (:repo
     "benchmark-init-el"
     :uri
     "https://github.com/dholm/benchmark-init-el.git")
    (:repo
     "avy"
     :uri
     "https://github.com/abo-abo/avy.git")
    (:repo
     "auto-yasnippet"
     :uri
     "https://github.com/abo-abo/auto-yasnippet.git")
    (:repo
     "auto-sudoedit"
     :uri
     "https://github.com/ncaq/auto-sudoedit.git")
    (:repo
     "auto-complete"
     :uri
     "https://github.com/auto-complete/auto-complete.git")
    (:repo
     "atomic-chrome"
     :uri
     "https://github.com/alpha22jp/atomic-chrome.git")
    (:repo
     "atom-one-dark-theme"
     :uri
     "https://github.com/jonathanchu/atom-one-dark-theme.git")
    (:repo
     "atom-dark-theme-emacs"
     :uri
     "https://github.com/whitlockjc/atom-dark-theme-emacs.git")
    (:repo
     "anaconda-mode"
     :uri
     "https://github.com/proofit404/anaconda-mode.git")
    (:repo
     "all-the-icons.el"
     :uri
     "https://github.com/domtronn/all-the-icons.el.git")
    (:repo
     "all-the-icons-dired"
     :uri
     "https://github.com/jtbm37/all-the-icons-dired.git")
    (:repo
     "alert"
     :uri
     "https://github.com/jwiegley/alert.git")
    (:repo
     "ac-php"
     :uri
     "https://github.com/xcwen/ac-php.git")
    (:repo
     "GitHub-Theme-for-Emacs"
     :uri
     "https://github.com/philiparvidsson/GitHub-Theme-for-Emacs.git")
    (:repo
     "doneburn-theme"
     :uri
     "https://github.com/manuel-uberti/doneburn-theme.git")
    (:repo
     "el2org"
     :uri
     "https://github.com/tumashu/el2org.git")
    (:repo
     "eldoc-eval"
     :uri
     "https://github.com/thierryvolpiatto/eldoc-eval.git")
    (:repo
     "elfeed"
     :uri
     "https://github.com/skeeto/elfeed.git")
    (:repo
     "elisp-refs"
     :uri
     "https://github.com/Wilfred/elisp-refs.git")
    (:repo
     "emacs-async"
     :uri
     "https://github.com/jwiegley/emacs-async.git")
    (:repo
     "emacs-color-themes"
     :uri
     "https://github.com/owainlewis/emacs-color-themes.git")
    (:repo
     "nsis-mode"
     :uri
     "https://github.com/mattfidler/nsis-mode.git")
    (:repo
     "makey"
     :uri
     "https://github.com/mickeynp/makey.git")
    (:repo
     "emacs-maple-preview"
     :uri
     "https://github.com/honmaple/emacs-maple-preview.git")
    (:repo
     "doom-modeline"
     :uri
     "https://github.com/seagle0128/doom-modeline.git")
    (:repo
     "apel"
     :uri
     "https://github.com/wanderlust/apel.git")
    (:repo
     "zeal-at-point"
     :uri
     "https://github.com/jinzhu/zeal-at-point.git")
    (:repo
     "search-web.el"
     :uri
     "https://github.com/tomoya/search-web.el.git")
    (:repo
     "org-reveal"
     :uri
     "https://github.com/yjwen/org-reveal.git")
    (:repo
     "entropy-undo-tree"
     :uri
     "https://github.com/c0001/entropy-undo-tree.git")
    (:repo
     "entropy-windresize"
     :uri
     "https://github.com/c0001/entropy-windresize.git")))


(provide 'owner)
